### ISSUE TITLE
Definir o nome final da ferramenta entre "FMM Saúde" ou "Saúde FMM"

### ISSUE THREAD

**Issue by pedrsv** [pedrsv/fmm_saude#12]
Os dois nomes são referenciados em locais diferentes da aplicação, deixando um pouco confuso saber qual o nome real. Após definir, refletir alterações do nome na ferramenta e linkar para este issue.

cc @Miguel0Bastos

**Comment by pedrsv** [comment]
A página inicial consta "FMMSaude", enquanto o PWA instalado está ficando com o nome "Saúde FMM".

**Comment by VictorGuedesJS** [comment]
FMM Saúde será o nome certo aplicação

<img width="472" alt="miguelitos-conversa" src="https://github.com/pedrsv/fmm_saude/assets/101725194/0c0f2b06-9bcf-4727-875e-d62bdab301ea">

**Comment by miguelitopy** [comment]
Privacidade de dados do Whatsapp vazado com sucesso kkkkkkkkk.

Complemento: Na segunda etapa do projeto, caso necessário, passamos por uma modelagem conceitual do projeto. Por enquanto vamos manter FMM SAÚDE.
