### ISSUE TITLE
O link "FMMSaude" está sem target nos termos de privacidade de dados

### ISSUE THREAD

**Issue by pedrsv** [pedrsv/fmm_saude#13]
Verificar qual o comportamento esperado para esse link quando ele foi adicionado, ou se ele realmente deve existir nessa página.

![image](https://github.com/pedrsv/fmm_saude/assets/110911485/5c1cfe64-9d2f-456a-998a-8df9d5749d4d)

**Comment by VictorGuedesJS** [comment]
Ajustado, o link foi retirado
