### ISSUE TITLE
Mensagem na tela de resultados retornando "undefined" ao digitar valores negativos para as pressões

### ISSUE THREAD

**Issue by Jgcs444** [pedrsv/fmm_saude#16]
- Caso minor, vale a pena verificar ?

**Comment by pedrsv** [comment]
Precisamos evitar que o valor retorne _undefined_.

Nesses casos, poderíamos discutir as seguintes possibilidades:
- Ocultar o trecho em que não foi possível calcular o resultado;
- Adicionar mensagem informando ao usuário que não foi possível calcular com os dados fornecidos.

Além disso, o issue #21 ou um derivado poderá auxiliar no tratamento da entrada do usuário para evitar ao máximo que os dados sejam inseridos incorretamente e cheguem a causar falhas na tela de resultados.

Levantem esses pontos na nossa próxima reunião interna, por favor.

cc @Miguel0Bastos, @VictorGuedesJS

**Comment by pedrsv** [comment]
Pontos discutidos na última reunião para serem executados nesta _issue_:
- Identificar e avisar o usuário quando dados de pressão inseridos forem negativos (ou inválidos).
- Impedir usuário de prosseguir até que dados válidos de pressão sejam inseridos.

**Comment by Jgcs444** [comment]
Após a implementação das restrições de entrada que permitem apenas números nos campos de pressão da ficha médica, a necessidade de tratativas adicionais para valores negativos foi eliminada, pois tais valores já não são mais aceitos.
