### ISSUE TITLE
Mudar o nome da Aplicação no codigo inteiro para FMM Saúde

### ISSUE THREAD

**Issue by VictorGuedesJS** [pedrsv/fmm_saude#17]
Devido a comunicação falha, o nome do pwa entre o codigo esta divergentes em algumas partes.

Corrigir para FMM Saúde, nome definido pelo time

**Comment by VictorGuedesJS** [comment]
Ajustado

**Comment by pedrsv** [comment]
The actual change was completed in e3ceac1 (#13) and adjusted in 1f6b150.
