### ISSUE TITLE
Porcentagem de probabilidade sempre retorna 0%

### ISSUE THREAD

**Issue by eumaciel8** [pedrsv/fmm_saude#18]
Colocando qualquer valor no final do cadastro está retornando valor 0%

**Comment by VictorGuedesJS** [comment]
A pressão não esta alterando o valor da probilidade de Hipertensão

**Comment by pedrsv** [comment]
> A pressão não esta alterando o valor da probilidade de Hipertensão

Isso é esperado ou você está apontando o problema?

Quando você puder disponibilizar internamente no nosso grupo, seria bom termos a tabela de pontuação das variáveis que influenciam a probabilidade do hipertensão.

Dessa forma o time de testes poderá criar mais casos de testes baseado nos resultados esperados. Isso não impacta a continuidade dos testes, mas é um bom recurso para se ter mais a frente.

Agradeço.

**Comment by VictorGuedesJS** [comment]
Esqueci de mandar a pontuação. XD

Bom, eu não coloquei porque não sei o quando isso afeta na probabilidade

**Comment by pedrsv** [comment]
@eumaciel8 Você pode retestar esse problema baseando-se nos dados que influenciam a porcentagem que foi fornecido no nosso grupo interno? E caso alguma porcentagem fora do esperado seja vista, reportar nesse mesmo issue, por favor.

**Comment by pedrsv** [comment]
@eumaciel8 Alguma atualização para essa _issue_?

**Comment by eumaciel8** [comment]
Fiz o reteste usando esse link (https://pedrsv.github.io/fmm_saude/index.html)
O problema ainda pesiste, testei todas possibilidades usando a tabela.

**Comment by eumaciel8** [comment]
Retestei novamente...
O resultado da porcentagem já retorna um valor, mas seguindo as seguintes condições.
Estarem marcadas pelo menos 1 ou ambas das doenças. 
cardíaca*
hipertensão*
No teste marcando as outras doenças e consumos (todo dia), e mensurando valores simulando pressão elevada, o resultado ainda retorna 0%.

**Comment by eumaciel8** [comment]
![Screenshot_20240514_182454_Samsung Internet](https://github.com/pedrsv/fmm_saude/assets/169402482/4e7ae30e-1ff2-4c69-a657-9bc5bba8f6cd)

![Screenshot_20240514_182443_Samsung Internet](https://github.com/pedrsv/fmm_saude/assets/169402482/f5c5d59d-d33e-4aa9-b54a-c95a56e88861)

![Screenshot_20240514_183917_Samsung Internet](https://github.com/pedrsv/fmm_saude/assets/169402482/136ab906-8dd3-45d3-b24a-8db7f9d166a6)

![Screenshot_20240514_183513_Samsung Internet](https://github.com/pedrsv/fmm_saude/assets/169402482/c1dcc204-5298-4bf9-897d-bdb5994e1bff)

**Comment by eumaciel8** [comment]
Em IMC - Coloquei um valor de peso ideal e tive resultado "sobre peso"

**Comment by pedrsv** [comment]
@eumaciel8 As capturas de tela são referentes à um único teste ou fazem parte de testes diferentes? Os horários das capturas de tela estão variando. É interessante sabermos exatamente o que foi inserido e o resultado retornado.

Para o caso do IMC, abre um _issue_ novo, por favor, descrevendo quais valores você inseriu, os resultados atuais e os resultados esperados. Vamos manter essa _issue_ atual apenas para o assunto de probabilidade de hipertensão.

**Comment by pedrsv** [comment]
@VictorGuedesJS Enquanto o Maciel confirma a sequência do teste, você pode verificar o relato de que só está calculando a probabilidade se tiver uma das duas doenças marcadas?
```
Estarem marcadas pelo menos 1 ou ambas das doenças.
cardíaca*
hipertensão*
No teste marcando as outras doenças e consumos (todo dia), e mensurando valores simulando pressão elevada, o resultado ainda retorna 0%.
```
De acordo com o relato, marcando doenças diferentes estaria retornando sempre 0 (zero).

**Comment by eumaciel8** [comment]
> @eumaciel8 As capturas de tela são referentes à um único teste ou fazem parte de testes diferentes? Os horários das capturas de tela estão variando. É interessante sabermos exatamente o que foi inserido e o resultado retornado.
> 
> Para o caso do IMC, abre um _issue_ novo, por favor, descrevendo quais valores você inseriu, os resultados atuais e os resultados esperados. Vamos manter essa _issue_ atual apenas para o assunto de probabilidade de hipertensão.

A tela de print foi de único teste.
Mas já havia testado outras.
O horário varia na tela de valores pq precisei voltar pra confirmar alguma valor no peso, pois achei estranho.

**Comment by eumaciel8** [comment]
DESCONSIDERAR ERRO NO CALCULO DE IMC.
Mensurei valor que realmente mede sobre peso.

**Comment by VictorGuedesJS** [comment]
@eumaciel8 
Fiz os ajustes para esse calculos, preciso que teste. Favor usar o Main-dev, o outro link do pedro

@pedrsv @eumaciel8 @Miguel0Bastos 
Tambem aumentei um pouco a pontuação. Mas nunca chegara a 100% a não ser que seja marcado hipertensão. Isso se deve a informações não poderem dizer 100% que a pessoa tem hipertensão, so uma probilidade.

Outro ponto é que a pressão elevada não influencia no calculo, isso foi conversado e a pressão no momento so indica o status momentaneo do paciente, aonde uma simples má alimentação, uma corrida e etc, influenciam para esses dados da pressão que pode ser elevado ou não, assim não sendo preciso o suficiente para colocar no calculo.

**Comment by pedrsv** [comment]
FYI: O outro link que usamos para testar a `main-dev` está inativo no momento.

Alternativamente você pode:
- Clonar o repositório na branch `main-dev` no seu computador para subir um servidor local e realizar os testes.
- Aguardar o link alternativo ficar disponível hoje a noite.

cc @eumaciel8

**Comment by eumaciel8** [comment]
Testes refeitos com base nos ajustes feito na última versão. Realizei os mesmos das versões anteriores.

Tudo certo!

Resultados em porcentagem.
Status: **PASS**
