### ISSUE TITLE
Ajustar Pontuação para caso, a pessoal tenha hipertensão como doença atual

### ISSUE THREAD

**Issue by VictorGuedesJS** [pedrsv/fmm_saude#19]
Ajustar Pontuação para caso, a pessoal tenha hipertensão como doença atual

**Comment by pedrsv** [comment]
Que tipo de ajuste na pontuação está sendo trabalhado nesse issue para esse cenário descrito?
(pra deixar documentado no issue)

**Comment by VictorGuedesJS** [comment]
Se ele tiver hipertensão, a probabilidade é de 100% de ele ter hipertensão.

kkkkkkkkk

**Comment by VictorGuedesJS** [comment]
Pontuação adicionada!
