### ISSUE TITLE
Permitindo entrada de carácteres no peso, altura, pressão sistólica e pressão diastólica. 

### ISSUE THREAD

**Issue by Wagnerlider113** [pedrsv/fmm_saude#21]
![IMG_7584](https://github.com/pedrsv/fmm_saude/assets/162245436/dbeee9c1-0646-4e1f-b4cb-67669550c8dc)

**Comment by pedrsv** [comment]
A falha foi encontrada ao usar o navegador Safari em um iPhone com iOS 17.4.1.

**Comment by pedrsv** [comment]
Também acontece ao usar o navegador _Chrome_ no iOS.
O teclado oferecido mostra todas as teclas liberadas, sem restrição de caracteres permitidos.

![image](https://github.com/pedrsv/fmm_saude/assets/110911485/f65a8e23-09ab-491a-ad6a-97313d4fd5f5)

**Comment by pedrsv** [comment]
Como resultado dessas últimas alterações, não é mais possível inserir caracteres não numéricos, pontos ou vírgulas nos campos de entrada, portanto decidimos fechar essa _issue_ atual como concluída.
