### ISSUE TITLE
Trocar redirecionamento automático por botão para o site da faculdade

### ISSUE THREAD

**Issue by pedrsv** [pedrsv/fmm_saude#24]
Para evitar os bloqueios de pop-up, como combinamos em reunião, o redirecionamento automático deve ser removido, e adicionado um botão na interface do usuário para que ele possa fazer a escolha de visitar o site.

Nome sugerido para o botão:
`Conhecer a FMM` (aberto a discussão)

Configurar para abrir em aba separada:
Exemplo: `target="_blank"` ou solução de mesmo efeito.

> **Importante:** Não esquecer de remover a mensagem fixa na tela final dizendo que o usuário será redirecionado automaticamente para o site da faculdade, pois este não é mais o comportamento esperado.

**Comment by VictorGuedesJS** [comment]
Configurar para abrir em aba separada:
Exemplo: target="_blank" ou solução de mesmo efeito.

Vai dar o mesmo de popup

**Comment by pedrsv** [comment]
O usuário clicar em um botão para abrir uma nova **aba** vai resultar no mesmo problema de abrir um **pop-up** automático?

Caso esteja testando isso agora, pode disponibilizar em uma branch separada baseada na `main-dev` para testarmos no deploy interno?

**Comment by pedrsv** [comment]
Atualmente nosso site tenta abrir automaticamente uma nova aba para o site da faculdade, porém essa ação automática é bloqueada pelos navegadores e exige uma ação extra do usuário para permitir a abertura da aba nova.

Em testes internos verifiquei dois casos possíveis:
1. Redirecionamento automático para o site **dentro da mesma aba**.
2. Redirecionamento por clique no botão pelo próprio usuário.

Me parece adequado adotar a estratégia de redirecionar dentro da mesma aba pois ainda segue o requisito original.

Também podemos adicionar um botão para o usuário clicar e ir, mas é desnecessário pois já seria automático.

@Miguel0Bastos, devo prosseguir com o **redirecionamento automático na mesma aba**? Caso sim, essa _issue_ será fechada e criarei outra para registrar a troca do modo de redirecionamento.

**Comment by miguelitopy** [comment]
Olá @pedrsv , devido aos conflitos existentes nos teste, vamos optar pelo requisito original: ser redirecionado automaticamente pela mesma aba.

Seria bom, apenas, ter um pequeno Delay a fim de que a pessoa consiga ler o aviso e assim ir para a página da faculdade.

**Comment by pedrsv** [comment]
Certo. Já existe um delay de 4 segundos. Vou apenas ajustar o modo de redirecionamento.

**Comment by pedrsv** [comment]
Fechando essa _issue_. Os ajustes discutidos serão feitos na _issue_ #28.
