### ISSUE TITLE
Tornar obrigatório o preenchimento dos campos da ficha médica

### ISSUE THREAD

**Issue by pedrsv** [pedrsv/fmm_saude#25]
Com o intuito de evitar alguns erros na tela de resultado pela ausência dos dados, decidimos tornar o preenchimento dos campos de peso, altura e pressões obrigatórios na ficha médica (_required_).

**Comment by VictorGuedesJS** [comment]
@pedrsv foi definido na reunião isso?

**Comment by pedrsv** [comment]
Sim, na reunião de ontem a noite.

Existe alguma preocupação em aberto sobre tornar esses campos obrigatórios? Se tiver, é bom trazer para discutirmos.

cc @VictorGuedesJS

**Comment by pedrsv** [comment]
Verifiquei que as _tags_ do _input_ da ficha médica já possuem o atributo ` required`  porém não estão tendo efeito nessa parte do formulário.

Em uma análise rápida identifiquei alguns pontos para serem investigados:
- Campos da ficha médica não estão em uma tag ` <form>` ;
- Botão ` Continuar`  não é do tipo ` submit`  como o da ficha cadastral.

O @Jgcs444 vai seguir a análise para identificar em que parte ocorre a incompatibilidade e como tornar os campos obrigatórios de forma adequada.
