### ISSUE TITLE
Adicionar placeholders nos campos da ficha médica

### ISSUE THREAD

**Issue by pedrsv** [pedrsv/fmm_saude#26]
Para ajudar o usuário a entender o que deve ser preenchido, concordamos em adicionar _placeholders_ nos campos de peso, altura e pressões da ficha médica.

Em conjunto com os tratamentos de entrada aplicados nas _issues_ #20 e #21, os _placeholders_ devem facilitar o entendimento do usuário sobre o que e como deve ser preenchido cada campo e evitar casos não cobertos.

**Comment by VictorGuedesJS** [comment]
Adicionado os placeholder nos inputs

<img width="519" alt="Screenshot 2024-05-13 124905" src="https://github.com/pedrsv/fmm_saude/assets/101725194/dd30eac5-f06f-4b3d-9fac-2090224b1f32">
