### ISSUE TITLE
O campo peso aceita qualquer caractere no browser do iOS

### ISSUE THREAD

**Issue by pedrsv** [pedrsv/fmm_saude#27]
O campo de Peso na ficha médica ainda está aceitando qualquer caractere nos navegadores do iOS.
Testando com Chrome e Safari.

iOS → **Aceitando qualquer caractere**
Android → Aceitando apenas ponto ( . )
Windows/Chrome → Aceitando apenas ponto ( . ) e vírgula ( , )

![image](https://github.com/pedrsv/fmm_saude/assets/110911485/51db9713-06a9-44b7-b381-6108d0326e27)

**Comment by VictorGuedesJS** [comment]
@pedrsv é pra deixar so ( . ) e ( , )? Além do numeros?

**Comment by pedrsv** [comment]
A prioridade é deixar números e ponto `.` já que o JavaScript trabalha com ponto.

Caso a vírgula permaneça, será necessário tratar internamente para substituir por ponto antes do cálculo caso ocorra alguma incompatibilidade.

**Comment by VictorGuedesJS** [comment]
Ajustado, foi colocado um nova função para inserir apenas um ponto que equivale a parte decimal do peso,
