### ISSUE TITLE
Tratativa para quando o valor 0 é informado nos campos da tela de cadastro médico ( Peso, altura, sistólica e diastólica) 

### ISSUE THREAD

**Issue by Jgcs444** [pedrsv/fmm_saude#29]
Adicionar tratativa para os seguintes campos, no momento em 0 for informado como valor: 

- Peso
- Altura
- Pressão Sistólica 
- Pressão Diastólica

**Comment by pedrsv** [comment]
**Motivo da tratativa:** quando todos os campos são definidos como 0 (zero), o trecho referente a eles na tela de resultados retorna ` undefined`  pois não é possível realizar as divisões e analisa-los dentro a um _range_ predefinido para mostrar nos resultados.
