### ISSUE TITLE
Aceitando números no campo nome

### ISSUE THREAD

**Issue by Wagnerlider113** [pedrsv/fmm_saude#31]
![IMG_7609](https://github.com/pedrsv/fmm_saude/assets/162245436/d7a6b3f9-8cbb-45dd-9d34-761b8a084a3b)

**Comment by VictorGuedesJS** [comment]
@Wagnerlider113 @pedrsv 

Acho que não temos como modificar isso, pois se impedir de aceitar números, possivelmente vai afetar caracteres especiais e não vai ser possivel colocar acentos nem "ç".

**Comment by pedrsv** [comment]
Não é uma boa ideia bloquear a entrada de caracteres especiais e acentos.

Analisando as páginas do Google e Facebook, identifiquei que estas páginas, apesar de não terem o mesmo objetivo de cadastro, também permitem a inserção de números nos campos de nome.

Considerando o baixo risco e baixo impacto da eventual inserção de números nesse campo do formulário, estou fechando esse _issue_ sem a implementação do recurso/_fix_ e sem planos de implementar por enquanto.
