### ISSUE TITLE
Doenças atuais/anteriores deve ser combinada ou adicionada já nas preexistentes

### ISSUE THREAD

**Issue by pedrsv** [pedrsv/fmm_saude#4]
No formulário de dados pessoais, as questões de doenças atuais/anteriores e comorbidades preexistentes precisam ser ajustadas conforme novo requisito.

> Por favor, alinhar previamente com o Analista de Projetos quais as modificações necessárias antes de modificar de fato.

**Comment by VictorGuedesJS** [comment]
colocar patologias na aba de doenças atuais, retirar anteriores do "Doenças atuais/Anteriores"
