### ISSUE TITLE
Adicionar cópia para e-mail interno ao salvar

### ISSUE THREAD

**Issue by pedrsv** [pedrsv/fmm_saude#6]
Issue criada para obter uma solução temporária para o salvamento de dados, visto que até então não estamos trabalhando com banco de dados no backend para armazenar os dados do formulário.

O stakeholder precisa salvar os dados de seus pacientes para poder fazer uma análises dos resultados após o evento e também conseguir ajudar seus pacientes em casos futuros.

**Comment by pedrsv** [comment]
Nós estamos trabalhando em uma solução interna para salvar os dados ao invés de enviar um e-mail para uma conta de e-mail interna para cada paciente que for preenchido. Mesmo quando nossa solução interna estiver funcionando, ainda poderemos trabalhar na solução de adicionar cópia (cc) para o e-mail interno se o cliente ainda precisar.

**Comment by miguelitopy** [comment]
Ciente!

Apenas lembrando, @pedrsv e @VictorGuedesJS , de após o resultado, ter uma opção de cair para o site da faculdade. Caso necessário, criar issue para isso.

**Comment by VictorGuedesJS** [comment]
@Miguel0Bastos isso ja foi adicionado

**Comment by pedrsv** [comment]
Redirecionamento para o site da faculdade adicionado no issue #5.
cc @Miguel0Bastos

**Comment by pedrsv** [comment]
Para salvar os dados do cadastro, conseguimos implementar uma solução temporária que alimenta uma planilha automaticamente e que já sendo testada no código desde algumas versões anteriores. Por limitações de tempo, não parece viável implementar a _feature_ de e-mail na primeira entrega desse projeto.

Enquanto isso, a equipe de desenvolvimento segue estudando os meios viáveis para a futura implementação do e-mail e outra _issue_ deverá ser aberta no futuro para endereçar isso. 

Com base nisso, decidimos fechar essa _issue_ por ter atingido o objetivo mais crítico, o armazenamento dos dados.
