### ISSUE TITLE
Adicionar recomendações com base na probabilidade de hipertensão

### ISSUE THREAD

**Issue by pedrsv** [pedrsv/fmm_saude#8]
Necessário feedback do setor da saúde para implementar as recomendações propostas corretamente.

cc @Miguel0Bastos

**Comment by miguelitopy** [comment]
Feedback não enviado pela parte da saúde. Para esta semana, não conseguiremos fazer esta issue por conta da ocupação deles no evento. 

Esta Issue ficará para a fase 2 do projeto. Caso ache necessário, pode fechá-la.

**Comment by pedrsv** [comment]
Como parte da limpeza das pendências da Entrega 1, estou fechando esse _issue_ pois não recebemos o material externo necessário em tempo hábil e o projeto (parte 1) já foi entregue sem o recurso.

Se for necessário, deverá ser levantado como requisito para a Entrega 2 em reuniões futuras.
